Prep release v0.15.0 (#454)
* Remove publish = false

* Bump versions and minor update to CHANGES.md

* Bump amino dependency! Will speedup build times :rocket:

* add license meta

* Some more meta data

* Mre meta data and `cargo +nightly fmt --`

* Fix rustdoc:
```
 Documenting tendermint v0.15.0 (/Users/ismail/IdeaProjects/tendermint-rs/tendermint)
error: `[Error::InvalidTrustThreshold]` cannot be resolved, ignoring it.
   --> tendermint/src/lite/types.rs:110:38
    |
110 |     /// In any other case we return [`Error::InvalidTrustThreshold`].
    |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot be resolved, ignoring
    |
```
* add comment in light-node lib

* refer to Readme

* delete requester.rs

* Add logo everywhere and link to next version for docs.rs

* make binary name explicit (in the Cargo.toml) and use the same name as in the crate

* Add rustdoc to rpc module

* Improve comment in lib / crate description

* update sled to 0.33

* Apply suggestions from code review

Co-authored-by: Alexander Simmerl <a.simmerl@gmail.com>

Co-authored-by: Alexander Simmerl <a.simmerl@gmail.com>